### PR TITLE
Seeker1437 webui service patch

### PR DESCRIPTION
**Pull request by Seeker1437**
This allows telling uWSGI to stop on SIGTERM instead of restarting

### CODE REVIEW

**Comment by Seeker1437** [comment]
Last commit overrides the `reload-mercy` and `worker-reload-mercy` parameters so that try terminate extremely quickly, adjust as you see fit.

**Comment by DOWRIGHTTV** [comment]
both the pid file and --die-on-term are required right?

**Comment by Seeker1437** [comment]
They are not ;)

**Review by DOWRIGHTTV — APPROVED** [review]
looks good.

**Pull request merged**
